In [5]:
import pandas as pd
import numpy as np
df=pd.read_csv('Cleaned_Exoplanets_data.csv')
df_new = pd.read_csv('Parallax.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6128 entries, 0 to 6127
Data columns (total 20 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   pl_name                                  6128 non-null   object
 1   Star's name                              6128 non-null   object
 2   sy_snum                                  6128 non-null   int64
 3   sy_pnum                                  6128 non-null   int64
 4   discoverymethod                          6128 non-null   object
 5   disc_year                                6127 non-null   float64
 6   pl_orb_period(in days)                   5776 non-null   float64
 7   pl_orb_period(in E.years)                6128 non-null   float64
 8   pl_orb_semi_maj_axis(in AU)              3821 non-null   float64
 9   pl_orb_eccent                            2586 non-null   float64
 10  pl_rad(in Earth Radius)                  4553 non-null   float64
 11  pl_bmass(in Earth Mass)                  3026 non-null   float64
 12  pl_dens(in (Earth mass/Earth radius))    4553 non-null   float64
 13  st_teff(in kelvin)                       5417 non-null   float64
 14  st_rad(in solar radius)                  5330 non-null   float64
 15  st_mass(in solar mass)                   5355 non-null   float64
 16  sy_dist(in Parsec)                       5993 non-null   float64
 17  pl_teff(in kelvin)                       3821 non-null   float64
 18  st_lum(in Solar luminosity)              6128 non-null   float64
 19  pl_recei_flux(in Earth's received flux)  3821 non-null   float64
dtypes: float64(15), int64(2), object(3)
memory usage: 957.6+ KB

In [ ]:
df_new.info()

In [ ]:
df.head()

,pl_name,Star's name,sy_snum,sy_pnum,discoverymethod,disc_year,pl_orb_period(in days),pl_orb_period(in E.years),pl_orb_semi_maj_axis(in AU),pl_orb_eccent,pl_rad(in Earth Radius),pl_bmass(in Earth Mass),pl_dens(in (Earth mass/Earth radius)),st_teff(in kelvin),st_rad(in solar radius),st_mass(in solar mass),sy_dist(in Parsec),pl_teff(in kelvin),st_lum(in Solar luminosity),pl_recei_flux(in Earth's received flux)
0,11 Com b,11 Com,2,1,Radial Velocity,2007.0,323.21000,0.884392,1.178,0.238,NaN,4914.898486,NaN,4874.0,13.76,2.09,93.1846,803.218264,95.866929,69.084121
1,11 UMi b,11 UMi,1,1,Radial Velocity,2009.0,516.21997,1.135049,1.530,0.080,NaN,4684.814200,NaN,4213.0,29.79,2.78,125.3210,896.380652,250.839943,107.155343
2,14 And b,14 And,1,1,Radial Velocity,2008.0,186.76000,0.511379,0.775,0.000,NaN,1131.151301,NaN,4888.0,11.55,1.78,75.4392,909.877272,68.324837,113.756233
3,14 Her b,14 Her,1,2,Radial Velocity,2002.0,1765.03890,4.843273,2.774,0.373,NaN,2559.472162,NaN,NaN,NaN,0.91,17.9323,0.000000,0.000000,0.000000
4,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996.0,798.50000,2.058023,1.660,0.680,NaN,565.737400,NaN,5750.0,1.13,1.08,21.1397,228.751790,1.252328,0.454467

In [ ]:
df_new.head()

In [ ]:
df.isnull().sum()

pl_name                                       0
Star's name                                   0
sy_snum                                       0
sy_pnum                                       0
discoverymethod                               0
disc_year                                     1
pl_orb_period(in days)                      352
pl_orb_period(in E.years)                     0
pl_orb_semi_maj_axis(in AU)                2307
pl_orb_eccent                              3542
pl_rad(in Earth Radius)                    1575
pl_bmass(in Earth Mass)                    3102
pl_dens(in (Earth mass/Earth radius))      1575
st_teff(in kelvin)                          711
st_rad(in solar radius)                     798
st_mass(in solar mass)                      773
sy_dist(in Parsec)                          135
pl_teff(in kelvin)                         2307
st_lum(in Solar luminosity)                   0
pl_recei_flux(in Earth's received flux)    2307
dtype: int64

In [ ]:
df_new.isnull().sum()

In [6]:
df.to_csv('new_cleaned_exoplanets.csv', index=False)
df_new.to_csv('new_parallax.csv', index=False)